apps/resume/urls.py
from django.urls import path
from django.conf.urls.static import static

from . import views
from .views import *


urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("dashboard", Dashboard.as_view(), name="dashboard"),
    path("logout", logout_request, name="logout"),
    path("update_data/<uuid:id>", UpdateDataView.as_view(), name="update_data"),
    path("add_another/<uuid:id>", AddAnother.as_view(), name="add_another"),
    path("create_resume/<int:id>", CreateResumeView.as_view(), name="create_resume"),
    path("image_upload/<uuid:id>", ImageUpload.as_view(), name="image_upload"),
    path(
        "deleteeducation/<uuid:id>/",
        views.DeleteEducation.as_view(),
        name="deleteeducation",
    ),
    path(
        "deleteexperience/<uuid:id>/",
        views.DeleteExperience.as_view(),
        name="deleteexperience",
    ),
    path(
        "deleteworksamples/<uuid:id>/",
        views.DeleteWorkSamples.as_view(),
        name="deleteworksamples",
    ),
    path(
        "deleteachievements/<uuid:id>/",
        views.DeleteAchievements.as_view(),
        name="deleteachievements",
    ),
    path(
        "deletecertificate/<uuid:id>/",
        views.DeleteCertificate.as_view(),
        name="deletecertificate",
    ),
    path("deleteskill/<uuid:id>/", views.DeleteSkills.as_view(), name="deleteskill"),
    path("deletehobbie/<uuid:id>/", views.DeleteHobbies.as_view(), name="deletehobbie"),
    #######################################################################################
    path(
        "template_preview/<uuid:id>",
        TemplatePreviews.as_view(),
        name="template_preview",
    ),
    path(
        "template_preview2/<uuid:id>",
        TemplatePreviews2.as_view(),
        name="template_preview2",
    ),
    path(
        "template_preview3/<uuid:id>",
        TemplatePreviews3.as_view(),
        name="template_preview3",
    ),
    path(
        "template_preview4/<uuid:id>",
        TemplatePreviews4.as_view(),
        name="template_preview4",
    ),
    path(
        "template_preview5/<uuid:id>",
        TemplatePreviews5.as_view(),
        name="template_preview5",
    ),
    path(
        "template_preview6/<uuid:id>",
        TemplatePreviews6.as_view(),
        name="template_preview6",
    ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume_maker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.resume.urls")),
    path("users/", include("apps.users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/resume/models.py
import uuid

from django.db import models
from django.utils.translation import ugettext_lazy as _

from apps.users.models import *

class ChooseTemplate(models.Model):
    name = models.CharField(max_length=800, null=True, blank=True)
    theme = models.ImageField(upload_to="theme/", blank=True)

    def __str__(self):
        return str(self.name)


class Resume(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    template = models.ForeignKey(
        ChooseTemplate, on_delete=models.CASCADE, blank=True, null=True
    )  # change
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True
    )  # change
    title = models.CharField(max_length=250)
    objective = models.TextField(max_length=1000)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ["id"]


class ResumeUserDetails(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=1000)
    email = models.EmailField()
    mobile = models.CharField(max_length=1000)
    date_of_birth = models.CharField(max_length=1000)
    address = models.CharField(max_length=1000)
    photo = models.ImageField(default="../static/images/default_avatar.png", blank=True)
    # photo = models.ImageField(upload_to='images/' ,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.resume)


class Education(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, null=True)
    qualification_name = models.CharField(max_length=100)
    year_of_passing = models.CharField(max_length=100)
    percentage_or_grade = models.CharField(max_length=100)
    university = models.CharField(max_length=100)

    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.resume)

    class Meta:
        ordering = ["date"]


class Experience(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, null=True)
    company_name = models.CharField(max_length=1000)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    designation = models.CharField(max_length=1000)
    role = models.CharField(max_length=2000)
    place = models.CharField(max_length=500)

    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.resume)

    class Meta:
        ordering = ["date"]


class WorkSamples(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, null=True)
    project_name = models.CharField(max_length=100)
    project_link = models.CharField(max_length=1000)
    technology = models.CharField(max_length=1000)
    description = models.TextField(max_length=1000)
    responsibilities = models.TextField(max_length=2000)
    
    
    logo = models.ImageField(upload_to="images/logos/")

    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.resume)

    class Meta:
        ordering = ["date"]


class Hobbies(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, null=True)
    hobbies = models.CharField(max_length=800)

    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.resume)

    class Meta:
        ordering = ["date"]


class Skills(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, null=True)
    skills = models.CharField(max_length=1000)

    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.resume)

    class Meta:
        ordering = ["date"]


class Certificate(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, null=True)
    certificate = models.CharField(max_length=1000)
    date_obtained = models.DateField(null=True, blank=True)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.resume)

    class Meta:
        ordering = ["date"]


class Achievements(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, null=True)
    achievements = models.CharField(max_length=1000)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.resume)

    class Meta:
        ordering = ["date"]

templates/resume/template_previews.html
<!doctype html>
{% load split_data %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> ​
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/css/template4/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <title>resume preview</title>
</head>
<body>
    <div class="wrapper">
        <div class="btnset">
            <a id="noprint" href="{% url 'update_data' resume.id %}"><button class="btn btn-primary">Edit
                    More</button></a>
            {% if request.user.is_authenticated %}
            <a href="{% url 'dashboard'  %}" id="noprint"><button class="btn btn-success">Dashboard</button></a>
            {% if not request.user.account_approved %}
            <a onclick="alert('pending approval')" href="#"><button class="btn btn-primary">Download</button></a>
            {% else %}
            <a href="#" id="noprint" class="btn btn-info download">
                Download</a>
            {% endif %}
            {% else %}
            <a href="{% url 'sign_up' resume.id %}"><button class="btn btn-primary">Download</button></a>
            {% endif %}
        </div>
        <div class="row">
            <div class="col-md-8">
                <div class="set">
                    <h2>CAREER OBJECTIVE</h2>
                    <ul class="achie">
                        
                        {{resume.objective|linebreaksbr}}
                    
                    </ul>

                    <h2>EXPERIENCES</h2>
                    {% for object in resume.experience_set.all %} 
                    {% if object.company_name == '' %} 
                    {% else %}
                        <h6 class=" font-weight-bold" name="company_name">Company Name :- {{ object.company_name }}</h6>
                    {% endif %} 
                    {% if object.designation == '' %}
                    {% else %}
                        <div class="" name="designation" placeholder="Designation..." onkeyup="AutoGrowTextArea(this)">
                        Designation :- {{object.designation}}</div>
                    {% endif %} 
                    {% if object.place == '' %} 
                    {% else %}
                        <div class="" name="place" placeholder="Place...">Place :- {{ object.place }}</div>
                    {% endif %}
                    {% if object.role == '' %} 
                    {% else %}
                    {% with object.role|split as split_data %}
                        <p class="font-weight-bold">Role :-</p>
                        <ul class="achie">
                            {% for data in split_data %}
                            <li>{{ data }}</li>
                            {% endfor %}
                        </ul>
                    {% endwith %}
                    {% endif %}
                    {% endfor %}

                    <h2 style="padding-top: 18px; padding-bottom: 7px;">WORK SAMPLES</h2>
                    {% for object in resume.worksamples_set.all %} {% if object.project_name == '' %} {% else %}
                    <h6 class=" font-weight-bold" name="project_name" value="{{object.project_name}}"
                        placeholder="Project name..."><span></span> Project Name :- {{ object.project_name }}</h6>
                    {% endif %} {% if object.project_link == '' %} {% else %}
                    <div class="" name="project_link" placeholder="project link...">Link :- {{ object.project_link}}
                    </div>
                    {% endif %} {% if object.technology == '' %} {% else %}
                    <div class="" name="technology" value="{{object.technology}}" placeholder="technology...">Technology
                        :- {{ object.technology }}</div>
                    {% endif %} {% if object.description == '' %} {% else %}
                    <p class="font-weight-bold">Description :-</p>
                    <ul class="achie">
                        <li>
                            {{ object.description }}
                        </li>
                    </ul>
                    {% endif %}

                    {% if object.responsibilities == '' %} {% else %}
                    {% with object.responsibilities|split as split_data %}
                    <p class=" font-weight-bold">Role and Responsibilities :-</p>
                    <ul>
                        {% for data in split_data %}
                        <li>{{ data }}</li>
                        {% endfor %}
                    </ul>
                    {% endwith %}
                    {% endif %}
                    {% endfor %}
                    <p style="break-inside: always;"></p>
                    <div>
                        {% if resume.achievements_set.all %}
                         {% for object in resume.achievements_set.all %}
                        {% if forloop.first and object.achievements != ''%}
                        <h2>ACHIEVEMENTS</h2>
                        {% endif %}
                        <ul class="achie">
                            {% if object.achievements == '' %}
                             {% else %}
                            <li>
                                {{object.achievements|linebreaksbr}}
                            </li>
                            {% endif %}
                        </ul>
                        {% endfor %} 
                        {% else %} 
                        {% endif %}
                         {% if resume.certificate_set.all %}
                        {% for object in resume.certificate_set.all %}
                        {% if forloop.first and object.certificate != ''%}
                        <h2>CERTIFICATE</h2>
                        {% endif %}
                        <ul class="achie">
                            {% if object.certificate == '' %}
                             {% else %}
                            <li>{{object.certificate|linebreaksbr}}</li>
                            {% endif %}
                        </ul>
                        {% endfor %}
                         {% else %} 
                         {% endif %}
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="profile-area">
                    <div class="avatar-upload">
                        <!-- <div class="avatar-preview">
                {% if resume.resumeuserdetails_set.get.photo.url is not null   %}
                <div id="imagePreview" style="background-image: url('{{resume.resumeuserdetails_set.get.photo.url}}')">
                  {% else %}
                <div id="imagePreview" >
                 {% endif %}
                </div>
              </div>
            </div> -->
                    </div>

                    <div class="test">
                        {% for object in resume.resumeuserdetails_set.all %}
                        <h3>{{resume.resumeuserdetails_set.all.first.full_name}}</h3>
                        <h6 style="font-size:15px">{{resume.title}}</h6>
                        {% comment %}
                        <h6 style="font-size:15px">{{object.email}}</h6> {% endcomment %}

                        <ul>
                            <!-- <li>Title :- {{resume.title}}</li> -->
                            <li>Email :- {{object.email}}</li>
                            <li>Phone :- {{object.mobile}}</li>
                            <li>Dob :- {{object.date_of_birth}}</li>
                            <li>Address :- {{object.address}}</li>
                        </ul>

                        <h2>EDUCATION</h2>
                        {% for object in resume.education_set.all %}
                        <ul>
                            {% if object.qualification_name == '' %} {% else %}
                            <li>Qualification :- {{object.qualification_name}}</li>
                            {% endif %} {% if object.university == '' %} {% else %}
                            <li>University :- {{object.university}}</li>
                            {% endif %} {% if object.year_of_passing == '' %} {% else %}
                            <li>Passing Year:- {{object.year_of_passing}}</li>
                            {% endif %} {% if object.percentage_or_grade == '' %} {% else %}
                            <li>Percentage :- {{object.percentage_or_grade}}</li>
                            {% endif %}
                        </ul>
                        {% endfor %}
                        <h2>SKILLS</h2>

                        <ul>
                            {% for object in resume.skills_set.all %} {% if object.skills == '' %} {% else %}
                            <li> {{object.skills}}</li>
                            {% endif %} {% endfor %}
                        </ul>

                        <h2>HOBBIES</h2>
                        <ul>
                            {% for object in resume.hobbies_set.all %} {% if object.hobbies == '' %} {% else %}
                            <li>
                                {{object.hobbies}}
                            </li>
                            {% endif %} {% endfor %}
                        </ul>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
    integrity="sha512-bnIvzh6FU75ZKxp0GXLH9bewza/OIw6dLVh9ICg0gogclmYGguQJWl8U30WpbsGTqbIiAwxTsbe76DErLq5EDQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
    $(".download").click(function () {
        $(".wrapper").css("margin-top", "-25px");
        $(".wrapper").css("margin-bottom", "0px");
        window.print()
    })
</script>
</html>

templates/resume/template_previews3.html
<!DOCTYPE html>
{% load split_data %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Responsive CV</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
        integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" type="text/css" href="/static/css/template3/sty.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<style type="text/css">
    .dow_btn button {
        font-size: 12px;
    }

    .dow_btn a {
        font-size: 12px;
    }

    .dow_btn {
        position: fixed;
        top: 50px;
        right: 5px;
    }

    @media print {
        #noprint {
            visibility: hidden;
        }
    }
</style>
<body>
    <div class="containers">
        <div class="name_sec">
            {% for object in resume.resumeuserdetails_set.all %}
            <h1>{{resume.resumeuserdetails_set.all.first.full_name}}</h1>
            <p>{{resume.title}}</p>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="left_Side">
                    <div class="contactInfo">
                        <h3 class="title">Contact Info</h3>
                        <ul>
                            {% for object in resume.resumeuserdetails_set.all %}
                            <li>
                                <div class="inputWithIcon inputIconBg"> <span><i class="fa fa-phone fa-lg fa-fw"
                                            aria-hidden="true"></i>{{object.mobile}}</span>
                                </div>
                            </li>
                            <li>
                                <div class="inputWithIcon inputIconBg"> <span><i class="fa fa-envelope-o"
                                            aria-hidden="true"></i>&nbsp;{{object.email}}</span>
                                </div>
                            </li>
                            <li>
                                <div class="inputWithIcon inputIconBg"> <span><i class="fa fa-globe"
                                            aria-hidden="true"></i>&nbsp;{{object.address}}</span>
                                </div>
                            </li>
                            <li>
                                <div class="inputWithIcon inputIconBg"> <span><i class="fa fa-birthday-cake"
                                            aria-hidden="true"></i>&nbsp;{{object.date_of_birth}}</span>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>

                        <div class="contactInfo education">
                            <h3 class="title">Education</h3>
                            <ul>
                                {% for object in resume.education_set.all %}
                                {% if object.qualification_name == '' %} {% else %}
                                <p><b>Qualification :-</b>{{object.qualification_name}}</p>
                                {% endif %} {% if object.university == '' %} {% else %}
                                <p><b>University :- </b>{{object.university}}</p>
                                {% endif %} {% if object.year_of_passing == '' %} {% else %}
                                <p><b>Passing Year :- </b>{{object.year_of_passing}}</p>
                                {% endif %} {% if object.percentage_or_grade == '' %} {% else %}
                                <p><b>Percentage :- </b>{{object.percentage_or_grade}}</p>
                                {% endif %}
                                {% endfor %}
                            </ul>
                            <br>
                        </div>
                        <!-- <div class="contactInfo language">
                                <h3 class="title">Language</h3>
                                <ul>
                                    <li> <span class="text">English</span>
                                        <ul>
                                            <li></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div> -->

                        <div class="about skills">
                            <h2 class="title2">Professional Skills</h2>
                            {% for object in resume.skills_set.all %}
                            <div class="box">
                                {% if object.skills == '' %} {% else %}

                                <p>{{object.skills}}</p>
                                {% endif %}
                            </div>
                            {% endfor %}

                            <div class="about interest">
                                <h2 class="title2">Interest</h2>
                                {% for object in resume.hobbies_set.all %}
                                <div class="inputWithIcon inputIconBg">
                                    {% if object.hobbies == '' %} {% else %}
                                    <p>{{object.hobbies}}</p>
                                    {% endif %}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="right_Side">
                    <div class="about">
                        <h2 class="title2">CAREER OBJECTIVE</h2>
                        <p>{{resume.objective|linebreaksbr}}</p>
                    </div>

                    <div class="about">
                        <h2 class="title2">Experience</h2>
                        {% for object in resume.experience_set.all %}
                        <div class="box">
                            <div class="year_company">
                                {% if object.company_name == '' %} {% else %}
                                <p><b>Company Name:-</b>{{ object.company_name }}</p>
                                {% endif %} {% if object.place == '' %} {% else %}
                                <p><b>Place :-</b>{{ object.place }}</p>
                                {% endif %}
                            </div>
                            <div class="text">
                                {% if object.designation == '' %} {% else %}
                                <p><b>Designation :-</b>{{ object.designation }}</p>
                                {% endif %}

                                {% if object.role == '' %} {% else %}
                                {% with object.role|split as split_data %}
                                <p><b>Role:-</b></p>
                                <ul class="role-area">
                                    {% for data in split_data %}
                                    <li>{{ data }}</li>
                                    {% endfor %}
                                </ul>
                                {% endwith %}
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                        <h2 class="title2">WORK SAMPLES</h2>
                        {% for object in resume.worksamples_set.all %}
                        <div class="box">
                            <div class="text">
                                {% if object.project_name == '' %} {% else %}
                                <p><b>Project Name:-</b>{{ object.project_name }}</p>
                                {% endif %} {% if object.project_link == '' %} {% else %}
                                <p><b>Project Link:-</b>{{ object.project_link }}</p>
                                {% endif %}
                                {% if object.technology == '' %} {% else %}
                                <p><b>Technology:-</b>{{ object.technology }}</p>
                                {% endif %}

                                {% if object.responsibilities == '' %} {% else %}
                                {% with object.responsibilities|split as split_data %}
                                <p><b>Responsibilities:-</b></p>
                                <ul class="role-area">
                                    {% for data in split_data %}
                                    <li>{{ data }}</li>
                                    {% endfor %}
                                </ul>
                                {% endwith %}
                                {% endif %}
                                {% if object.description == '' %} {% else %}
                                <p><b>Description:-</b>{{ object.description }}</p>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    <div class="about">
                        {% if resume.achievements_set.all %}
                        {% for object in resume.achievements_set.all %}
                        {% if forloop.first and object.achievements != ''%}
                        <h2 class="title2">ACHIEVEMENTS</h2>
                        {% endif %} 
                        {% if object.achievements == '' %}
                        {% else %}
                        <p>{{object.achievements|linebreaksbr}}</p>
                        {% endif %}
                        {% endfor %} 
                        {% else %}
                        {% endif %}
                    </div>

                    <div class="about">
                        {% if resume.certificate_set.all %}
                        {% for object in resume.certificate_set.all %} 
                        {% if forloop.first and object.certificate != ''%}
                        <h2 class="title2">CERTIFICATE</h2>
                        {% endif %} 
                        {% if object.certificate == '' %} 
                        {% else %}
                        <p>{{object.certificate|linebreaksbr}}</p>
                        {% endif %} 
                        {% endfor %} 
                        {% else %} 
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="dow_btn">
        <a id="noprint" href="{% url 'update_data' resume.id %}"><button class="btn btn-primary">Edit
                More</button></a> 
                {% if request.user.is_authenticated %}
                 <a href="{% url 'dashboard'  %}"  id="noprint"><button class="btn btn-success">Dashboard</button></a> 
            {% if not request.user.account_approved %}
        <a onclick="alert('pending approval')" href="#"><button class="btn btn-primary">Download</button></a> 
        {% else %}
        <a href="#" id="noprint" class="btn btn-info download">Download</a>
             {% endif %}
              {% else %}
        <a href="{% url 'sign_up' resume.id %}"><button class="btn btn-primary">Download</button></a> 
        {% endif %}
    </div>
</body>
<script>
    $(".download").click(function () {
        $(".wrapper").css("margin-top", "-25px");
        $(".wrapper").css("margin-bottom", "0px");
        window.print()
    })
</script>
</html>